/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Fictional Healthcare Demo Data for AarogyaFlow
 * 1 Main Hospital, 8 Doctors, 20 Patients, 50 Visits, Tokens, and Documents.
 * ALL DATA IS COMPLETELY FICTIONAL FOR CLINICAL INTAKE DEMONSTRATION.
 */

import { Hospital, Doctor, Patient, Visit, QueueToken, UploadedDocument } from '../types';

export const DEMO_HOSPITALS: Hospital[] = [
  {
    hospitalId: 'HOSP001',
    name: 'LifeBridge Multispeciality Hospital',
    address: 'Plot 14-B, Sector 5, Medical Enclave, Bengaluru, Karnataka 560029',
    city: 'Bengaluru',
    state: 'Karnataka',
    latitude: 12.9352,
    longitude: 77.6245,
    departments: ['Cardiology', 'General Medicine', 'Orthopedics', 'Neurology', 'Dermatology', 'Pediatrics'],
    phone: '+91 80 2699 5000',
    emergencyAvailable: true,
    status: 'Open 24/7',
    distanceKm: 2.4,
  },
  {
    hospitalId: 'HOSP002',
    name: 'AIIMS Regional Public Healthcare Centre',
    address: 'Ring Road, Near Metro Junction, New Delhi 110029',
    city: 'New Delhi',
    state: 'Delhi',
    latitude: 28.5672,
    longitude: 77.2100,
    departments: ['General Medicine', 'Cardiology', 'Pediatrics', 'Orthopedics', 'Dermatology'],
    phone: '+91 11 2658 8500',
    emergencyAvailable: true,
    status: 'Open 24/7',
    distanceKm: 4.8,
  },
  {
    hospitalId: 'HOSP003',
    name: 'Victoria District Government Hospital',
    address: 'Fort Road, Near City Market, Bengaluru, Karnataka 560002',
    city: 'Bengaluru',
    state: 'Karnataka',
    latitude: 12.9620,
    longitude: 77.5750,
    departments: ['General Medicine', 'Orthopedics', 'Neurology', 'Pediatrics'],
    phone: '+91 80 2670 1150',
    emergencyAvailable: true,
    status: 'OPD Active',
    distanceKm: 6.2,
  },
  {
    hospitalId: 'HOSP004',
    name: 'Manipal Community Health Institute',
    address: '98 HAL Old Airport Road, Kodihalli, Bengaluru, Karnataka 560017',
    city: 'Bengaluru',
    state: 'Karnataka',
    latitude: 12.9592,
    longitude: 77.6496,
    departments: ['Cardiology', 'General Medicine', 'Gastroenterology', 'Pulmonology', 'ENT'],
    phone: '+91 80 2502 4444',
    emergencyAvailable: true,
    status: 'Open 24/7',
    distanceKm: 3.1,
  },
  {
    hospitalId: 'HOSP005',
    name: 'Safdarjung Super Speciality OPD Centre',
    address: 'Ansari Nagar West, Ring Road, New Delhi 110029',
    city: 'New Delhi',
    state: 'Delhi',
    latitude: 28.5700,
    longitude: 77.2065,
    departments: ['General Medicine', 'Orthopedics', 'Pediatrics', 'Ophthalmology', 'Cardiology'],
    phone: '+91 11 2670 7444',
    emergencyAvailable: true,
    status: 'Open 24/7',
    distanceKm: 5.2,
  },
  {
    hospitalId: 'HOSP006',
    name: 'KEM Municipal General Hospital & Medical College',
    address: 'Acharya Donde Marg, Parel, Mumbai, Maharashtra 400012',
    city: 'Mumbai',
    state: 'Maharashtra',
    latitude: 19.0028,
    longitude: 72.8423,
    departments: ['General Medicine', 'Cardiology', 'Neurology', 'Orthopedics', 'Dermatology'],
    phone: '+91 22 2410 7000',
    emergencyAvailable: true,
    status: 'Open 24/7',
    distanceKm: 3.8,
  },
  {
    hospitalId: 'HOSP007',
    name: 'Lilavati Hospital & Research Centre',
    address: 'A-791, Bandra Reclamation, Bandra West, Mumbai, Maharashtra 400050',
    city: 'Mumbai',
    state: 'Maharashtra',
    latitude: 19.0510,
    longitude: 72.8285,
    departments: ['Cardiology', 'Oncology', 'Neurology', 'General Medicine', 'Pediatrics'],
    phone: '+91 22 2675 1000',
    emergencyAvailable: true,
    status: 'Open 24/7',
    distanceKm: 4.5,
  },
  {
    hospitalId: 'HOSP008',
    name: 'Nizam\'s Institute of Medical Sciences (NIMS)',
    address: 'Punjagutta Road, Hyderabad, Telangana 500082',
    city: 'Hyderabad',
    state: 'Telangana',
    latitude: 17.4243,
    longitude: 78.4526,
    departments: ['Cardiology', 'Neurology', 'General Medicine', 'Orthopedics', 'Nephrology'],
    phone: '+91 40 2348 9000',
    emergencyAvailable: true,
    status: 'Open 24/7',
    distanceKm: 4.1,
  },
  {
    hospitalId: 'HOSP009',
    name: 'Rajiv Gandhi Government General Hospital',
    address: 'EVR Periyar Salai, Park Town, Chennai, Tamil Nadu 600003',
    city: 'Chennai',
    state: 'Tamil Nadu',
    latitude: 13.0818,
    longitude: 80.2785,
    departments: ['General Medicine', 'Cardiology', 'Orthopedics', 'Pediatrics', 'Dermatology'],
    phone: '+91 44 2530 5000',
    emergencyAvailable: true,
    status: 'Open 24/7',
    distanceKm: 3.5,
  },
  {
    hospitalId: 'HOSP010',
    name: 'Sassoon General Hospital & Medical College',
    address: 'Near Pune Railway Station, Sassoon Road, Pune, Maharashtra 411001',
    city: 'Pune',
    state: 'Maharashtra',
    latitude: 18.5284,
    longitude: 73.8742,
    departments: ['General Medicine', 'Orthopedics', 'Cardiology', 'Neurology', 'Pediatrics'],
    phone: '+91 20 2612 8000',
    emergencyAvailable: true,
    status: 'Open 24/7',
    distanceKm: 2.9,
  },
];

export const DEMO_DOCTORS: Doctor[] = [
  {
    doctorId: 'D001',
    firebaseUid: 'uid_doc_ananya',
    name: 'Dr. Ananya Rao',
    qualification: 'MBBS, MD, DM (Cardiology)',
    specialization: 'Interventional Cardiology & Preventive Heart Care',
    department: 'Cardiology',
    hospitalId: 'HOSP001',
    phone: '+91 98450 12345',
    email: 'ananya.rao@aarogyahospital.gov.in',
    languages: ['English', 'Kannada', 'Hindi', 'Telugu'],
    availability: 'Available',
    currentStatus: 'Consulting OPD Room 204',
    roomNumber: 'OPD 204 (2nd Floor)',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200',
  },
  {
    doctorId: 'D002',
    firebaseUid: 'uid_doc_rahul',
    name: 'Dr. Rahul Kumar',
    qualification: 'MBBS, MD (General Medicine)',
    specialization: 'Internal Medicine, Diabetes & Lifestyle Disorders',
    department: 'General Medicine',
    hospitalId: 'HOSP001',
    phone: '+91 98450 67890',
    email: 'rahul.kumar@aarogyahospital.gov.in',
    languages: ['English', 'Hindi', 'Punjabi'],
    availability: 'Available',
    currentStatus: 'Consulting OPD Room 102',
    roomNumber: 'OPD 102 (Ground Floor)',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
  },
  {
    doctorId: 'D003',
    firebaseUid: 'uid_doc_suresh',
    name: 'Dr. Suresh Patel',
    qualification: 'MBBS, MS (Orthopedics), M.Ch',
    specialization: 'Joint Replacement & Spine Arthroscopy',
    department: 'Orthopedics',
    hospitalId: 'HOSP001',
    phone: '+91 98450 33445',
    email: 'suresh.patel@aarogyahospital.gov.in',
    languages: ['English', 'Gujarati', 'Hindi'],
    availability: 'In Consultation',
    currentStatus: 'Reviewing Post-Op Cases',
    roomNumber: 'OPD 108 (Ground Floor)',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200',
  },
  {
    doctorId: 'D004',
    firebaseUid: 'uid_doc_priya',
    name: 'Dr. Priya Nair',
    qualification: 'MBBS, MD, DM (Neurology)',
    specialization: 'Stroke Prevention, Epilepsy & Headaches',
    department: 'Neurology',
    hospitalId: 'HOSP001',
    phone: '+91 98450 55667',
    email: 'priya.nair@aarogyahospital.gov.in',
    languages: ['English', 'Malayalam', 'Tamil', 'Hindi'],
    availability: 'Available',
    currentStatus: 'Ready for Next Intake',
    roomNumber: 'OPD 210 (2nd Floor)',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1594824813627-2c93d93a89e0?auto=format&fit=crop&q=80&w=200',
  },
  {
    doctorId: 'D005',
    firebaseUid: 'uid_doc_vikram',
    name: 'Dr. Vikram Sharma',
    qualification: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
    specialization: 'Clinical Dermatology & Allergy Manifestations',
    department: 'Dermatology',
    hospitalId: 'HOSP001',
    phone: '+91 98450 77889',
    email: 'vikram.sharma@aarogyahospital.gov.in',
    languages: ['English', 'Hindi', 'Marathi'],
    availability: 'Available',
    currentStatus: 'Consulting OPD Room 115',
    roomNumber: 'OPD 115 (Ground Floor)',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200',
  },
  {
    doctorId: 'D006',
    firebaseUid: 'uid_doc_sunita',
    name: 'Dr. Sunita Menon',
    qualification: 'MBBS, DCH, MD (Pediatrics)',
    specialization: 'Pediatric Infectious Diseases & Neonatology',
    department: 'Pediatrics',
    hospitalId: 'HOSP001',
    phone: '+91 98450 99001',
    email: 'sunita.menon@aarogyahospital.gov.in',
    languages: ['English', 'Malayalam', 'Kannada', 'Hindi'],
    availability: 'Available',
    currentStatus: 'Consulting OPD Room 105',
    roomNumber: 'OPD 105 (Ground Floor)',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200',
  },
  {
    doctorId: 'D007',
    firebaseUid: 'uid_doc_arvind',
    name: 'Dr. Arvind Swamy',
    qualification: 'MBBS, MD (Cardiology)',
    specialization: 'Cardiac Electrophysiology & Arrhythmia',
    department: 'Cardiology',
    hospitalId: 'HOSP001',
    phone: '+91 98450 22334',
    email: 'arvind.swamy@aarogyahospital.gov.in',
    languages: ['English', 'Tamil', 'Telugu'],
    availability: 'On Break',
    currentStatus: 'Cath Lab Procedure',
    roomNumber: 'OPD 205 (2nd Floor)',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200',
  },
  {
    doctorId: 'D008',
    firebaseUid: 'uid_doc_fatima',
    name: 'Dr. Fatima Sheikh',
    qualification: 'MBBS, MD (General Medicine)',
    specialization: 'Acute Febrile Illness & Tropical Medicine',
    department: 'General Medicine',
    hospitalId: 'HOSP001',
    phone: '+91 98450 44556',
    email: 'fatima.sheikh@aarogyahospital.gov.in',
    languages: ['English', 'Hindi', 'Urdu', 'Bengali'],
    availability: 'Available',
    currentStatus: 'Consulting OPD Room 103',
    roomNumber: 'OPD 103 (Ground Floor)',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1594824813627-2c93d93a89e0?auto=format&fit=crop&q=80&w=200',
  },
];

// Sample Medical Documents with simulated original doctor letterheads and lab reports
export const DEMO_DOCUMENTS: UploadedDocument[] = [
  {
    documentId: 'DOC001',
    patientId: 'P001001',
    visitId: 'V0001',
    documentType: 'Prescription',
    fileName: 'Previous_Rx_DrAnanyaRao_Cardiology_Jul2026.pdf',
    fileURL: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=600',
    fileSize: '420 KB',
    uploadedBy: 'Patient (Ravi Kumar)',
    uploadedAt: '2026-07-02T10:15:00Z',
    notes: 'Prescription for Telmisartan 40mg once daily + lifestyle modification by Dr. Ananya Rao',
  },
  {
    documentId: 'DOC002',
    patientId: 'P001001',
    visitId: 'V0002',
    documentType: 'Lab Report',
    fileName: 'Lipid_Profile_And_ECG_Aug2026.pdf',
    fileURL: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=600',
    fileSize: '1.2 MB',
    uploadedBy: 'Lab Reception',
    uploadedAt: '2026-08-12T14:30:00Z',
    notes: 'Total Cholesterol: 218 mg/dL, Triglycerides: 190 mg/dL, Resting ECG: Normal Sinus Rhythm',
  },
  {
    documentId: 'DOC003',
    patientId: 'P001002',
    documentType: 'Scan Report',
    fileName: 'Bilateral_Knee_XRay_AP_Lateral.pdf',
    fileURL: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=600',
    fileSize: '2.4 MB',
    uploadedBy: 'Radiology Dept',
    uploadedAt: '2026-06-20T11:00:00Z',
    notes: 'Grade II Osteoarthritis changes in medial joint space',
  },
];

// Primary Demo Patient: Ravi Kumar (Section 44)
export const DEMO_PATIENTS: Patient[] = [
  {
    patientId: 'P001001',
    firebaseUid: 'uid_pat_ravi_kumar',
    name: 'Ravi Kumar',
    age: 46,
    gender: 'Male',
    phone: '+91 98765 43210',
    email: 'ravi.kumar46@example.com',
    preferredLanguage: 'en',
    bloodGroup: 'B+ve',
    allergies: ['Penicillin (mild skin rash)'],
    existingConditions: ['Hypertension (diagnosed 2 years ago)', 'Mild dyslipidemia'],
    emergencyContact: {
      name: 'Sunita Kumar',
      relation: 'Spouse',
      phone: '+91 98765 43211',
    },
    createdAt: '2026-01-15T09:00:00Z',
    status: 'Under Intake',
  },
  {
    patientId: 'P001002',
    firebaseUid: 'uid_pat_lakshmi',
    name: 'Lakshmi Devi',
    age: 58,
    gender: 'Female',
    phone: '+91 98765 11223',
    email: 'lakshmi.devi58@example.com',
    preferredLanguage: 'kn',
    bloodGroup: 'O+ve',
    allergies: ['None known'],
    existingConditions: ['Bilateral Knee Osteoarthritis', 'Type 2 Diabetes'],
    emergencyContact: {
      name: 'Venkatesh Murthy',
      relation: 'Son',
      phone: '+91 98765 11224',
    },
    createdAt: '2026-02-10T10:00:00Z',
    status: 'Active',
  },
  {
    patientId: 'P001003',
    firebaseUid: 'uid_pat_faizan',
    name: 'Mohammed Faizan',
    age: 34,
    gender: 'Male',
    phone: '+91 98765 33445',
    email: 'faizan.m@example.com',
    preferredLanguage: 'hi',
    bloodGroup: 'A+ve',
    allergies: ['Sulfa drugs'],
    existingConditions: ['Seasonal Allergic Rhinitis'],
    emergencyContact: {
      name: 'Amina Faizan',
      relation: 'Spouse',
      phone: '+91 98765 33446',
    },
    createdAt: '2026-03-05T11:20:00Z',
    status: 'Active',
  },
  {
    patientId: 'P001004',
    firebaseUid: 'uid_pat_rajeshwari',
    name: 'Rajeshwari Iyer',
    age: 62,
    gender: 'Female',
    phone: '+91 98765 55667',
    email: 'rajeshwari.iyer@example.com',
    preferredLanguage: 'ta',
    bloodGroup: 'AB+ve',
    allergies: ['Aspirin'],
    existingConditions: ['Type 2 Diabetes Mellitus (10 yrs)', 'Diabetic Neuropathy'],
    emergencyContact: {
      name: 'Karthik Iyer',
      relation: 'Son',
      phone: '+91 98765 55668',
    },
    createdAt: '2026-03-12T14:00:00Z',
    status: 'Active',
  },
  {
    patientId: 'P001005',
    firebaseUid: 'uid_pat_amit',
    name: 'Amit Verma',
    age: 29,
    gender: 'Male',
    phone: '+91 98765 77889',
    email: 'amit.verma29@example.com',
    preferredLanguage: 'hi',
    bloodGroup: 'B+ve',
    allergies: ['None known'],
    existingConditions: ['Eczema / Contact Dermatitis'],
    emergencyContact: {
      name: 'Ramesh Verma',
      relation: 'Father',
      phone: '+91 98765 77890',
    },
    createdAt: '2026-04-01T08:30:00Z',
    status: 'Active',
  },
  {
    patientId: 'P001006',
    firebaseUid: 'uid_pat_anita',
    name: 'Anita Das',
    age: 41,
    gender: 'Female',
    phone: '+91 98765 99001',
    email: 'anita.das41@example.com',
    preferredLanguage: 'bn',
    bloodGroup: 'O-ve',
    allergies: ['None known'],
    existingConditions: ['Frequent Migraines'],
    emergencyContact: {
      name: 'Subhash Das',
      relation: 'Husband',
      phone: '+91 98765 99002',
    },
    createdAt: '2026-04-14T10:15:00Z',
    status: 'Active',
  },
  {
    patientId: 'P001007',
    firebaseUid: 'uid_pat_gurpreet',
    name: 'Gurpreet Singh',
    age: 52,
    gender: 'Male',
    phone: '+91 98765 11335',
    email: 'gurpreet.singh@example.com',
    preferredLanguage: 'pa',
    bloodGroup: 'A+ve',
    allergies: ['Dust mites'],
    existingConditions: ['Asthma (mild persistent)'],
    emergencyContact: {
      name: 'Harpreet Kaur',
      relation: 'Spouse',
      phone: '+91 98765 11336',
    },
    createdAt: '2026-04-22T13:40:00Z',
    status: 'Active',
  },
  {
    patientId: 'P001008',
    firebaseUid: 'uid_pat_sneha',
    name: 'Sneha Kulkarni',
    age: 33,
    gender: 'Female',
    phone: '+91 98765 22446',
    email: 'sneha.kulkarni@example.com',
    preferredLanguage: 'mr',
    bloodGroup: 'B-ve',
    allergies: ['Ibuprofen'],
    existingConditions: ['Hypothyroidism'],
    emergencyContact: {
      name: 'Pradeep Kulkarni',
      relation: 'Brother',
      phone: '+91 98765 22447',
    },
    createdAt: '2026-05-02T11:00:00Z',
    status: 'Active',
  },
  {
    patientId: 'P001009',
    firebaseUid: 'uid_pat_pranav',
    name: 'Pranav Nair',
    age: 12,
    gender: 'Male',
    phone: '+91 98765 33557',
    email: 'nair.family@example.com',
    preferredLanguage: 'ml',
    bloodGroup: 'O+ve',
    allergies: ['Peanuts'],
    existingConditions: ['Childhood Bronchial Hyperreactivity'],
    emergencyContact: {
      name: 'Suresh Nair',
      relation: 'Father',
      phone: '+91 98765 33558',
    },
    createdAt: '2026-05-18T15:20:00Z',
    status: 'Active',
  },
  {
    patientId: 'P001010',
    firebaseUid: 'uid_pat_bhavna',
    name: 'Bhavna Patel',
    age: 49,
    gender: 'Female',
    phone: '+91 98765 44668',
    email: 'bhavna.patel@example.com',
    preferredLanguage: 'gu',
    bloodGroup: 'A-ve',
    allergies: ['None known'],
    existingConditions: ['Osteopenia', 'Mild Hypertension'],
    emergencyContact: {
      name: 'Chirag Patel',
      relation: 'Spouse',
      phone: '+91 98765 44669',
    },
    createdAt: '2026-05-29T09:45:00Z',
    status: 'Active',
  },
  // Additional patients to satisfy approximately 20
  ...Array.from({ length: 10 }).map((_, idx) => {
    const num = idx + 11;
    const names = [
      'Gopal Krishna', 'Deepa Somani', 'Kavita Chawla', 'Manoj Gowda', 'Pooja Reddy',
      'Farooq Abdullah', 'Tanvi Deshmukh', 'Subhashree Sen', 'Jaswinder Gill', 'Hitesh Zala'
    ];
    const languages = ['te', 'hi', 'pa', 'kn', 'te', 'hi', 'mr', 'bn', 'pa', 'gu'];
    return {
      patientId: `P0010${num < 10 ? '0' + num : num}`,
      firebaseUid: `uid_pat_${num}`,
      name: names[idx],
      age: 25 + (idx * 4),
      gender: (idx % 2 === 0 ? 'Male' : 'Female') as 'Male' | 'Female',
      phone: `+91 98765 ${55000 + num}`,
      email: `patient${num}@example.com`,
      preferredLanguage: languages[idx],
      bloodGroup: ['A+', 'B+', 'O+', 'AB+'][idx % 4] + 've',
      allergies: idx % 3 === 0 ? ['Dust / Pollen'] : ['None known'],
      existingConditions: idx % 2 === 0 ? ['Mild Acidity'] : ['None reported'],
      emergencyContact: {
        name: 'Family Member',
        relation: 'Relative',
        phone: `+91 98765 ${66000 + num}`,
      },
      createdAt: `2026-06-0${(idx % 9) + 1}T10:00:00Z`,
      status: 'Active' as const,
    };
  })
];

// Previous consultations for Ravi Kumar (Section 10 & 30)
export const DEMO_VISITS: Visit[] = [
  // Previous Visit 1 for Ravi Kumar
  {
    visitId: 'V0001',
    patientId: 'P001001',
    patientName: 'Ravi Kumar',
    patientAge: 46,
    patientGender: 'Male',
    doctorId: 'D001',
    doctorName: 'Dr. Ananya Rao',
    hospitalId: 'HOSP001',
    hospitalName: 'LifeBridge Multispeciality Hospital',
    department: 'Cardiology',
    date: '02 Jul 2026',
    tokenNumber: 'C-018',
    chiefComplaint: 'Occasional mild chest tightness on climbing stairs',
    symptoms: ['Mild chest tightness', 'Exertional fatigue'],
    painScore: 4,
    patientResponses: [
      { id: 't1', question: 'When did the tightness start?', answer: 'Noticed it around 3 days ago when taking stairs at work.', timestamp: '2026-07-02T10:05:00Z', mode: 'text' },
      { id: 't2', question: 'Does it subside when you rest?', answer: 'Yes, after resting for 5 minutes it eases up.', timestamp: '2026-07-02T10:07:00Z', mode: 'text' },
    ],
    aiSummary: {
      chiefComplaint: 'Mild chest tightness on exertion',
      structuredSymptoms: ['Mild chest tightness', 'Exertional fatigue'],
      onset: '3 days prior to visit',
      painScore: 4,
      clinicalNarrative: '46yo male with 2-year history of hypertension presenting with exertional substernal tightness relieving with rest. No resting pain, diaphoresis, or syncope reported.',
      attentionFlags: ['Exertional chest tightness in hypertensive male — evaluate for stable angina / ischemia'],
      suggestedDepartment: 'Cardiology',
      departmentConfidence: 86,
      departmentReasoning: 'Cardiovascular history and exertional chest symptoms.',
      suggestedDoctorId: 'D001',
      suggestedDoctorName: 'Dr. Ananya Rao',
      statusLabel: 'AI Generated — Verified by Dr. Ananya Rao',
      generatedAt: '2026-07-02T10:10:00Z',
    },
    aiRedFlags: ['Exertional chest tightness'],
    doctorNotes: 'Resting BP 142/90 mmHg. Heart sounds normal. No basal rales. ECG shows mild LVH voltage criteria, no acute ST-T changes. Advised lipid panel and echo.',
    doctorAssessment: 'Exertional Angina (Class I-II) / Essential Hypertension under-controlled',
    doctorDiagnosis: 'Hypertensive Heart Disease / Mild Exertional Angina',
    prescription: {
      medicines: [
        { name: 'Tab Telmisartan', dosage: '40 mg', frequency: 'Once daily (Morning)', duration: '30 days', instructions: 'After breakfast' },
        { name: 'Tab Atorvastatin', dosage: '10 mg', frequency: 'Once daily (Night)', duration: '30 days', instructions: 'After dinner' },
        { name: 'Tab Sorbitrate', dosage: '5 mg', frequency: 'Sublingual as SOS', duration: 'SOS', instructions: 'Only if chest tightness persists >5 mins' },
      ],
      advice: 'Low salt, low cholesterol diet. Avoid heavy sudden physical exertion. Return immediately if pain occurs at rest or radiates to arm.',
    },
    uploadedDocuments: [DEMO_DOCUMENTS[0]],
    status: 'Completed',
    createdAt: '2026-07-02T10:00:00Z',
    verifiedAt: '2026-07-02T10:35:00Z',
  },
  // Previous Visit 2 for Ravi Kumar
  {
    visitId: 'V0002',
    patientId: 'P001001',
    patientName: 'Ravi Kumar',
    patientAge: 46,
    patientGender: 'Male',
    doctorId: 'D002',
    doctorName: 'Dr. Rahul Kumar',
    hospitalId: 'HOSP001',
    hospitalName: 'LifeBridge Multispeciality Hospital',
    department: 'General Medicine',
    date: '12 Aug 2026',
    tokenNumber: 'GM-042',
    chiefComplaint: 'Follow-up blood pressure check and lipid review',
    symptoms: ['Occasional morning headache'],
    painScore: 2,
    patientResponses: [
      { id: 't1', question: 'How has your blood pressure been measuring at home?', answer: 'Around 138/88 mmHg. Feeling mostly fine.', timestamp: '2026-08-12T11:00:00Z', mode: 'text' },
    ],
    aiSummary: {
      chiefComplaint: 'Routine hypertension and lipid follow-up',
      structuredSymptoms: ['Occasional morning headache'],
      onset: 'Intermittent past 2 weeks',
      painScore: 2,
      clinicalNarrative: 'Routine medical review. Patient adhering to Telmisartan and Atorvastatin. Reports good compliance.',
      attentionFlags: [],
      suggestedDepartment: 'General Medicine',
      departmentConfidence: 91,
      departmentReasoning: 'Follow-up chronic disease management.',
      suggestedDoctorId: 'D002',
      suggestedDoctorName: 'Dr. Rahul Kumar',
      statusLabel: 'AI Generated — Verified by Dr. Rahul Kumar',
      generatedAt: '2026-08-12T11:05:00Z',
    },
    aiRedFlags: [],
    doctorNotes: 'BP 136/86 mmHg. Reports good adherence. Labs reviewed: LDL 132 mg/dL, Triglycerides 190. Continue current therapy.',
    doctorAssessment: 'Controlled Essential Hypertension on therapy',
    doctorDiagnosis: 'Essential Hypertension (Stage 1) & Dyslipidemia',
    prescription: {
      medicines: [
        { name: 'Tab Telmisartan', dosage: '40 mg', frequency: 'Once daily', duration: '60 days', instructions: 'Morning' },
        { name: 'Tab Atorvastatin', dosage: '10 mg', frequency: 'Once daily', duration: '60 days', instructions: 'Night' },
      ],
      advice: 'Continue 30 min daily brisk walking. Follow-up after 3 months.',
    },
    uploadedDocuments: [DEMO_DOCUMENTS[1]],
    status: 'Completed',
    createdAt: '2026-08-12T10:45:00Z',
    verifiedAt: '2026-08-12T11:25:00Z',
  },
  // CURRENT PREPARED DEMO CASE FOR RAVI KUMAR (Section 44)
  {
    visitId: 'V0003',
    patientId: 'P001001',
    patientName: 'Ravi Kumar',
    patientAge: 46,
    patientGender: 'Male',
    doctorId: 'D001',
    doctorName: 'Dr. Ananya Rao',
    hospitalId: 'HOSP001',
    hospitalName: 'LifeBridge Multispeciality Hospital',
    department: 'Cardiology',
    date: '08 Sep 2026 (Today)',
    tokenNumber: 'C-024',
    chiefComplaint: 'Chest pain since yesterday with breathlessness and cold sweating',
    symptoms: ['Chest pain', 'Breathlessness', 'Cold Sweating', 'Heaviness in upper chest'],
    painScore: 7,
    patientResponses: [
      { id: 't1', question: 'When did the chest pain start?', answer: 'Yesterday evening around 7 PM after dinner, and it became much worse today morning.', timestamp: '2026-09-08T09:15:00Z', mode: 'voice' },
      { id: 't2', question: 'Where exactly is the pain and does it radiate?', answer: 'Centre of my chest, feels like heavy pressing, spreads towards my left shoulder and inner arm.', timestamp: '2026-09-08T09:17:00Z', mode: 'voice' },
      { id: 't3', question: 'Are you having breathlessness or cold sweating?', answer: 'Yes, both. Breathing feels tight when walking even a few steps, and I had sudden cold sweat.', timestamp: '2026-09-08T09:19:00Z', mode: 'voice' },
      { id: 't4', question: 'Have you taken any medicine or had relief with rest?', answer: 'Took one Sorbitrate SOS tablet 2 hours ago with very little relief. Pain is around 7 out of 10.', timestamp: '2026-09-08T09:21:00Z', mode: 'text' },
    ],
    aiSummary: {
      chiefComplaint: 'Chest pain since yesterday with breathlessness and cold sweating',
      structuredSymptoms: ['Retrosternal chest pressure / heaviness', 'Radiation to left arm & shoulder', 'Shortness of breath (dyspnea)', 'Cold sweating (diaphoresis)'],
      onset: 'Yesterday evening (~14 hours duration), worsening today',
      painScore: 7,
      clinicalNarrative: '46-year-old male with established hypertension presenting with acute onset retrosternal chest tightness radiating to left shoulder and arm, accompanied by cold sweating and exertional dyspnea. Minimal relief with sublingual nitrate.',
      attentionFlags: [
        '⚠ ATTENTION: Chest pain with breathlessness & diaphoresis — High clinical concern for Acute Coronary Syndrome (ACS / Unstable Angina / NSTEMI)',
        '⚠ ATTENTION: Reported left arm radiation and inadequate response to sublingual nitrate',
      ],
      suggestedDepartment: 'Cardiology',
      departmentConfidence: 94,
      departmentReasoning: 'Acute cardiac presentation with high-risk red-flag symptoms and continuity with previous treating cardiologist (Dr. Ananya Rao).',
      suggestedDoctorId: 'D001',
      suggestedDoctorName: 'Dr. Ananya Rao',
      statusLabel: 'AI Generated — Requires Doctor Verification',
      generatedAt: '2026-09-08T09:22:00Z',
    },
    aiRedFlags: [
      'Chest pain with breathlessness and diaphoresis',
      'Left upper extremity pain radiation',
      'High self-reported pain score (7/10)',
    ],
    comparisonWithPrevious: {
      sincePreviousVisit: [
        '+ New symptom: Acute shortness of breath (breathlessness)',
        '+ New symptom: Cold sweating (diaphoresis)',
        '+ Pain escalated from 4/10 (exertional) to 7/10 (resting & prolonged)',
        '+ Pain now radiates to left shoulder and arm (previously confined to substernal)',
        'No change in reported drug allergies (Penicillin allergy unchanged)',
      ],
      painComparison: 'Pain worsened from 4/10 to 7/10 since July 2026 visit',
      newSymptoms: ['Breathlessness', 'Diaphoresis (cold sweats)', 'Left arm radiation'],
      resolvedSymptoms: [],
      allergyChange: 'No new allergies reported',
    },
    uploadedDocuments: [DEMO_DOCUMENTS[0], DEMO_DOCUMENTS[1]],
    status: 'Waiting',
    createdAt: '2026-09-08T09:23:00Z',
  },
  // Additional visits across multiple patients and departments to satisfy 50 visits
  ...Array.from({ length: 47 }).map((_, i) => {
    const vId = `V00${i + 4 < 10 ? '0' + (i + 4) : i + 4}`;
    const depts = ['General Medicine', 'Cardiology', 'Orthopedics', 'Neurology', 'Dermatology', 'Pediatrics'];
    const dept = depts[i % depts.length];
    const doc = DEMO_DOCTORS.find(d => d.department === dept) || DEMO_DOCTORS[0];
    const pat = DEMO_PATIENTS[(i + 1) % DEMO_PATIENTS.length];
    const complaints = [
      'High grade fever with body ache since 3 days',
      'Severe bilateral knee joint stiffness',
      'Persistent throbbing unilateral headache with photophobia',
      'Itchy erythematous rash over forearm',
      'Recurrent cough with wheezing at night',
      'Burning epigastric pain after meals',
      'Dizziness and postural unsteadiness',
      'Lower back ache radiating to right leg',
    ];
    const complaint = complaints[i % complaints.length];
    const pain = 2 + (i % 7);
    const day = ((i * 3) % 28) + 1;
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'];
    const month = months[i % months.length];

    return {
      visitId: vId,
      patientId: pat.patientId,
      patientName: pat.name,
      patientAge: pat.age,
      patientGender: pat.gender,
      doctorId: doc.doctorId,
      doctorName: doc.name,
      hospitalId: 'HOSP001',
      hospitalName: 'LifeBridge Multispeciality Hospital',
      department: dept,
      date: `${day < 10 ? '0' + day : day} ${month} 2026`,
      tokenNumber: `${dept.substring(0, 2).toUpperCase()}-0${10 + i}`,
      chiefComplaint: complaint,
      symptoms: [complaint.split(' since ')[0]],
      painScore: pain,
      patientResponses: [
        { id: `t_${i}_1`, question: 'How long have you felt this?', answer: 'Started a few days ago.', timestamp: '2026-07-10T10:00:00Z', mode: 'guided' as const }
      ],
      aiSummary: {
        chiefComplaint: complaint,
        structuredSymptoms: [complaint],
        onset: '3 to 5 days',
        painScore: pain,
        clinicalNarrative: `Patient reports ${complaint}. Relevant for ${dept} outpatient review.`,
        attentionFlags: pain >= 8 ? [`Severe pain score reported (${pain}/10)`] : [],
        suggestedDepartment: dept,
        departmentConfidence: 85,
        departmentReasoning: `Clinical presentation aligns with ${dept}.`,
        suggestedDoctorId: doc.doctorId,
        suggestedDoctorName: doc.name,
        statusLabel: 'AI Generated — Requires Doctor Verification',
        generatedAt: '2026-07-10T10:02:00Z',
      },
      aiRedFlags: pain >= 8 ? ['High pain score reported'] : [],
      doctorNotes: `Clinical review completed. Vitals stable. Advised standard medical management.`,
      doctorAssessment: `${complaint} under clinical review`,
      doctorDiagnosis: `${dept} standard evaluation`,
      uploadedDocuments: [],
      status: 'Completed' as const,
      createdAt: `2026-07-10T09:30:00Z`,
      verifiedAt: `2026-07-10T10:15:00Z`,
    };
  })
];

// Active Queue Tokens for today
export const DEMO_TOKENS: QueueToken[] = [
  {
    tokenId: 'TOK001',
    hospitalId: 'HOSP001',
    department: 'Cardiology',
    doctorId: 'D001',
    doctorName: 'Dr. Ananya Rao',
    patientId: 'P001001',
    patientName: 'Ravi Kumar',
    patientAge: 46,
    patientGender: 'Male',
    tokenNumber: 'C-024',
    chiefComplaint: 'Chest pain since yesterday with breathlessness and cold sweating',
    attentionFlag: '⚠ Attention: Chest pain + breathlessness & cold sweats',
    status: 'Waiting',
    createdAt: '2026-09-08T09:23:00Z',
    estimatedWaitMinutes: 5,
    visitId: 'V0003',
  },
  {
    tokenId: 'TOK002',
    hospitalId: 'HOSP001',
    department: 'Cardiology',
    doctorId: 'D001',
    doctorName: 'Dr. Ananya Rao',
    patientId: 'P001004',
    patientName: 'Rajeshwari Iyer',
    patientAge: 62,
    patientGender: 'Female',
    tokenNumber: 'C-025',
    chiefComplaint: 'Palpitations and dizziness on exertion',
    attentionFlag: undefined,
    status: 'Waiting',
    createdAt: '2026-09-08T09:30:00Z',
    estimatedWaitMinutes: 15,
    visitId: 'V0004',
  },
  {
    tokenId: 'TOK003',
    hospitalId: 'HOSP001',
    department: 'General Medicine',
    doctorId: 'D002',
    doctorName: 'Dr. Rahul Kumar',
    patientId: 'P001003',
    patientName: 'Mohammed Faizan',
    patientAge: 34,
    patientGender: 'Male',
    tokenNumber: 'GM-012',
    chiefComplaint: 'High fever (102°F) with chills and severe body ache for 3 days',
    attentionFlag: 'High fever > 102°F with severe myalgia',
    status: 'Waiting',
    createdAt: '2026-09-08T09:35:00Z',
    estimatedWaitMinutes: 10,
    visitId: 'V0005',
  },
  {
    tokenId: 'TOK004',
    hospitalId: 'HOSP001',
    department: 'Orthopedics',
    doctorId: 'D003',
    doctorName: 'Dr. Suresh Patel',
    patientId: 'P001002',
    patientName: 'Lakshmi Devi',
    patientAge: 58,
    patientGender: 'Female',
    tokenNumber: 'O-008',
    chiefComplaint: 'Severe right knee swelling and inability to bear weight',
    attentionFlag: undefined,
    status: 'In Progress',
    createdAt: '2026-09-08T09:10:00Z',
    estimatedWaitMinutes: 0,
    visitId: 'V0006',
  },
  {
    tokenId: 'TOK005',
    hospitalId: 'HOSP001',
    department: 'Neurology',
    doctorId: 'D004',
    doctorName: 'Dr. Priya Nair',
    patientId: 'P001006',
    patientName: 'Anita Das',
    patientAge: 41,
    patientGender: 'Female',
    tokenNumber: 'N-005',
    chiefComplaint: 'Severe throbbing right temporal headache with nausea and visual aura',
    attentionFlag: undefined,
    status: 'Waiting',
    createdAt: '2026-09-08T09:40:00Z',
    estimatedWaitMinutes: 20,
    visitId: 'V0007',
  },
];
